apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-site
spec:
  replicas: 1
  selector:
    matchLabels:
      app: static-site
  template:
    metadata:
      labels:
        app: static-site
    spec:
      containers:
        - name: static-site
          image: my-static-site:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: static-site-service
spec:
  type: ClusterIP
  selector:
    app: static-site
  ports:
    - port: 3347
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: static-site-http
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints.address: ":3346"
spec:
  rules:
    - host: static-site.116.203.217.202.sslip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: static-site-service
                port:
                  number: 3347
