apiVersion: apps/v1
kind: Deployment
metadata:
  name: bun-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bun-app
  template:
    metadata:
      labels:
        app: bun-app
    spec:
      containers:
        - name: bun-app
          image: localhost:5000/k3s-bun-app
          ports:
          - containerPort: 3000
          env:
          - name: HOSTNAME
            value: 0.0.0.0
---
apiVersion: v1
kind: Service
metadata:
  name: bun-app-service
spec: 
  selector:
    app: bun-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
